# Generated by Django 2.2 on 2020-02-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_remove_user_confrim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='messages',
        ),
        migrations.AddField(
            model_name='comment',
            name='messages',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='TheMessages', to='wall_app.Message'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='TheUsers', to='wall_app.User'),
            preserve_default=False,
        ),
    ]
